language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 5.5.9
      env: setup=lowest
    - php: 5.5.9
      env: setup=stable

sudo: false

install:
  composer install --no-interaction --prefer-source

script: vendor/bin/phpunit
