language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  exclude:
    - php: 7.0

before_script:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - phpunit

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'